config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "accounts"

  root 'test#index'
  resources :books

  resources :users, param: :nickname, only: [:index, :show]# do

end

app/models/book.rb
class Book < ActiveRecord::Base
  # model relation
  has_many :readings
  has_many :users, through: :readings

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # model relation
  has_many :readings
  has_many :books, through: :readings

  # login getter and setter
    attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  #nickname is unique
  validates_uniqueness_of :nickname
  validates_presence_of :nickname


  # login as nickname or email
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["nickname = :value OR lower(email) = lower(:value)", { value: login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #call method before sign in
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #setting strong parameters, and nickname allows
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :nickname, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :nickname, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :nickname, :password, :password_confirmation, :current_password) }
  end

  # devise redirect URLs after sign in
  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    search = RBooks::Search.new(1076114325239656110)
    result = search.get do |b|
      b[:isbn] = params['book']['isbn']
      b[:formatVersion] = 2
    end
    p result

    #@book = Book.new(book_params)
    @book = Book.find_or_create_by(isbn: result['Items'][0]['isbn']) do |b|
      b.title = result['Items'][0]['title']
      b.author = result['Items'][0]['author']
      b.publisher = result['Items'][0]['publisherName']
    end

    @book.users << current_user unless @book.users.exists?(id: current_user.id)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  # before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  # before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(nickname: params[:nickname])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">toshogakari</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#"><%= current_user.nickname if user_signed_in? %></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
            <!-- <%= current_user.email if user_signed_in? %> -->
              <li><%= link_to t('devise.registrations.edit_profile'), edit_user_registration_path %></li>
              <li><%= link_to t('devise.sign_out'), destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to t('devise.registrations.sign_up'), new_user_registration_path %></li>
              <li><%= link_to t('devise.sessions.sign_in'), new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Toshogakari</title>

  <!-- CDN installation -->
  <%= javascript_include_tag "//code.jquery.com/jquery-2.1.4.min.js" %>
  <%= javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <!-- Rails Default settings -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <article>
  <div class="container">
    <%= yield %>
  </div>
  </article>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/top/index.html.erb
<h1>Hello_(：3」∠)_</h1>
<p>Top page is here ｽﾞｲ₍₍(ง˘ω˘)ว⁾⁾ｽﾞｲ</p>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Information</h1>

<table>
  <thead>
  <tr>
    <th>Nickname</th>
    <th>Email</th>
    <th>Sign_in_count</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.email %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= link_to 'Show', user_path(user.nickname) %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Sign_in_count:</strong>
  <%= @user.sign_in_count %>
</p>

<%= link_to 'Edit', edit_user_registration_path(@user) %> |
<%= link_to 'Back', users_path %>